
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d
version: '2.4'
networks:
    br0:
      external: true
      
services:
  ip_discover:
    container_name: ip_discover
    image: chunhui2001/alpine:3.13.python-3.8.7
    hostname: ip_discover
    mem_limit: 10m
    ports:
      - 17110:8080
    #command: ["sh", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    entrypoint: ["python3", "/root/microee-ipserver/ip-discover.py"]
    volumes:
      # centos7 as the host and container with selinux enabled.
      # 在 centos7 下需执行: chcon -Rt svirt_sandbox_file_t config/
      - ./microee-ipserver:/root/microee-ipserver:ro
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.208
